In [1]:
import pandas as pd

In [2]:
data={"user":['ankit','raj','raju','ram'],
       "salary":[2300,4500,8700,4500]
     }

In [3]:
data

{'user': ['ankit', 'raj', 'raju', 'ram'], 'salary': [2300, 4500, 8700, 4500]}

In [4]:
df=pd.DataFrame(data)

In [5]:
type(df["user"])

pandas.core.series.Series

In [6]:
df2=pd.read_csv("sample_data1 - Sheet1.csv")

In [7]:
df2.groupby("Region")["Monthly_Sales"].sum()

Region
East     377000.0
North    245000.0
South    363000.0
West      92000.0
Name: Monthly_Sales, dtype: float64

Scenario: Corporate Employee Performance Dashboard
A company tracks quarterly performance scores of employees across different departments.
The HR analytics team wants to analyze this dataset to identify top performers, departmental trends, and highlight exceptional scores.

Dataset
The dataset contains the following columns:
- Employee: Name of the employee
- Department: Department they belong to (Sales, HR, IT, Finance, etc.)
- Quarter: The quarter in which the performance score was recorded (Q1, Q2, Q3, Q4)
- Score: Performance score (numeric value)

Tasks
- Filtering (Core Corporate Skill)
- Find employees with Score > 90 (exceptional performers).
- Filter records for the Sales department only.
- Sorting (Power Moment)
- Sort employees by Score in descending order to rank performance.
- Sort by Department first, then Score to see departmental rankings.
- Grouping (Core Corporate Skill)
- Group by Department and calculate the average score per department.
- Group by Quarter and find the maximum score achieved in each quarter.

Business Context
- Filtering helps HR identify exceptional performers and focus on specific departments.
- Sorting creates clear performance rankings, useful for promotions or recognition programs.
- Grouping reveals departmental strengths and quarterly performance trends, guiding training and resource allocation.

In [8]:
employee=pd.read_csv("Dataset  - Sheet1.csv")

In [9]:
employee

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
1    Priya         HR      Q1     85
2     John         IT      Q1     92
3     Sara    Finance      Q1     88
4    David      Sales      Q2     95
5    Meera         HR      Q2     80
6     Alex         IT      Q2     70
7     Ravi    Finance      Q2     90
8     Neha      Sales      Q3     99
9    Karan         IT      Q3     76

In [10]:
exceptional=employee[employee["Score"]>90]

In [11]:
exceptional

  Employee Department Quarter  Score
2     John         IT      Q1     92
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [12]:
sales=employee[employee["Department"] == "Sales"]

In [13]:
sales

  Employee Department Quarter  Score
0     Amit      Sales      Q1     78
4    David      Sales      Q2     95
8     Neha      Sales      Q3     99

In [14]:
rank=employee.sort_values(by="Score", ascending=False)

In [15]:
rank

  Employee Department Quarter  Score
8     Neha      Sales      Q3     99
4    David      Sales      Q2     95
2     John         IT      Q1     92
7     Ravi    Finance      Q2     90
3     Sara    Finance      Q1     88
1    Priya         HR      Q1     85
5    Meera         HR      Q2     80
0     Amit      Sales      Q1     78
9    Karan         IT      Q3     76
6     Alex         IT      Q2     70

In [16]:
dept_rank=employee .sort_values(by=["Department", "Score"], ascending=[True, False])

In [17]:
dept_rank

  Employee Department Quarter  Score
7     Ravi    Finance      Q2     90
3     Sara    Finance      Q1     88
1    Priya         HR      Q1     85
5    Meera         HR      Q2     80
2     John         IT      Q1     92
9    Karan         IT      Q3     76
6     Alex         IT      Q2     70
8     Neha      Sales      Q3     99
4    David      Sales      Q2     95
0     Amit      Sales      Q1     78

In [18]:
customer=pd.read_csv("Customers1 - Sheet1.csv")

In [19]:
sales=pd.read_csv("Sales1 - Sheet1.csv")

In [20]:
support=pd.read_csv("support1 - Sheet1.csv")

In [22]:
# Inspect datasets
print(customer.shape)
print(sales.shape)
print(support.shape)

print(customer.columns)
print(sales.columns)
print(support.columns)

print(customer.isnull().sum())
print(sales.isnull().sum())
print(support.isnull().sum())

(8, 5)
(8, 6)
(8, 4)
Index(['CustomerID', 'Name', 'Age', 'Region', 'SignupDate'], dtype='object')
Index(['OrderID', 'CustomerID', 'Product', 'Quantity', 'Price', 'OrderDate'], dtype='object')
Index(['TicketID', 'CustomerID', 'IssueType', 'ResolutionTime'], dtype='object')
CustomerID    0
Name          0
Age           1
Region        0
SignupDate    0
dtype: int64
OrderID       0
CustomerID    0
Product       0
Quantity      0
Price         0
OrderDate     0
dtype: int64
TicketID          0
CustomerID        0
IssueType         0
ResolutionTime    0
dtype: int64

In [23]:
sales

  OrderID CustomerID     Product  Quantity  Price   OrderDate
0   O1001       C001      Laptop         2  55000  2023-04-10
1   O1002       C002      Mobile         1  25000  2023-04-12
2   O1003       C003      Tablet         3  15000  2023-05-01
3   O1004       C004      Laptop         1  60000  2023-05-15
4   O1005       C005      Mobile         2  22000  2023-06-05
5   O1006       C006  Headphones         5   2000  2023-06-10
6   O1007       C007      Laptop         1  58000  2023-07-02
7   O1008       C008      Tablet         2  18000  2023-07-20

In [25]:
price_arr=sales["Price"].to_numpy()

In [26]:
discount=price_arr*0.9

In [27]:
sales["discount"]=discount

In [28]:
sales["discount"]

0    49500.0
1    22500.0
2    13500.0
3    54000.0
4    19800.0
5     1800.0
6    52200.0
7    16200.0
Name: discount, dtype: float64

In [29]:
sales

  OrderID CustomerID     Product  Quantity  Price   OrderDate  discount
0   O1001       C001      Laptop         2  55000  2023-04-10   49500.0
1   O1002       C002      Mobile         1  25000  2023-04-12   22500.0
2   O1003       C003      Tablet         3  15000  2023-05-01   13500.0
3   O1004       C004      Laptop         1  60000  2023-05-15   54000.0
4   O1005       C005      Mobile         2  22000  2023-06-05   19800.0
5   O1006       C006  Headphones         5   2000  2023-06-10    1800.0
6   O1007       C007      Laptop         1  58000  2023-07-02   52200.0
7   O1008       C008      Tablet         2  18000  2023-07-20   16200.0

In [31]:
sales['revenue']=sales['Quantity']*sales['Price']

In [32]:
sales

,OrderID,CustomerID,Product,Quantity,Price,OrderDate,discount,revenue
0,O1001,C001,Laptop,2,55000,2023-04-10,49500.0,110000
1,O1002,C002,Mobile,1,25000,2023-04-12,22500.0,25000
2,O1003,C003,Tablet,3,15000,2023-05-01,13500.0,45000
3,O1004,C004,Laptop,1,60000,2023-05-15,54000.0,60000
4,O1005,C005,Mobile,2,22000,2023-06-05,19800.0,44000
5,O1006,C006,Headphones,5,2000,2023-06-10,1800.0,10000
6,O1007,C007,Laptop,1,58000,2023-07-02,52200.0,58000
7,O1008,C008,Tablet,2,18000,2023-07-20,16200.0,36000

In [33]:
customer

  CustomerID   Name   Age Region  SignupDate
0       C001   Amit  28.0  North  2023-01-15
1       C002  Priya  35.0  South  2022-11-20
2       C003   John   NaN   East  2023-03-05
3       C004   Sara  42.0   West  2021-07-12
4       C005  David  30.0  North  2023-02-10
5       C006  Meera  27.0  South  2022-09-18
6       C007   Alex  33.0   East  2023-01-25
7       C008   Ravi  40.0   West  2022-12-01

In [46]:
sales['OrderDate'] = pd.to_datetime(sales['OrderDate'])

jan_orders = sales[
    (sales['OrderDate'].dt.month == 1) &
    (sales['OrderDate'].dt.year == 2025)
]

print(jan_orders)

Empty DataFrame
Columns: [OrderID, CustomerID, Product, Quantity, Price, OrderDate, discount, revenue]
Index: []

In [50]:
north_customers = customer[customer['Region'] == "North"]

In [55]:
north_customers

  CustomerID   Name   Age Region  SignupDate
0       C001   Amit  None  North  2023-01-15
4       C005  David  None  North  2023-02-10

In [53]:
high_value_orders = sales[sales['revenue'] > 10000]

In [54]:
high_value_orders

  OrderID CustomerID Product  Quantity  Price  OrderDate  discount  revenue
0   O1001       C001  Laptop         2  55000 2023-04-10   49500.0   110000
1   O1002       C002  Mobile         1  25000 2023-04-12   22500.0    25000
2   O1003       C003  Tablet         3  15000 2023-05-01   13500.0    45000
3   O1004       C004  Laptop         1  60000 2023-05-15   54000.0    60000
4   O1005       C005  Mobile         2  22000 2023-06-05   19800.0    44000
6   O1007       C007  Laptop         1  58000 2023-07-02   52200.0    58000
7   O1008       C008  Tablet         2  18000 2023-07-20   16200.0    36000

In [57]:
customer['SignupDate'] = pd.to_datetime(customer['SignupDate'])

customers_sorted = customer.sort_values(by='SignupDate')

In [58]:
customers_sorted

  CustomerID   Name   Age Region SignupDate
3       C004   Sara  None   West 2021-07-12
5       C006  Meera  None  South 2022-09-18
1       C002  Priya  None  South 2022-11-20
7       C008   Ravi  None   West 2022-12-01
0       C001   Amit  None  North 2023-01-15
6       C007   Alex  None   East 2023-01-25
4       C005  David  None  North 2023-02-10
2       C003   John  None   East 2023-03-05

In [60]:
sales_sorted = sales.sort_values(by='revenue', ascending=False)

In [61]:
sales_sorted

,OrderID,CustomerID,Product,Quantity,Price,OrderDate,discount,revenue
0,O1001,C001,Laptop,2,55000,2023-04-10,49500.0,110000
3,O1004,C004,Laptop,1,60000,2023-05-15,54000.0,60000
6,O1007,C007,Laptop,1,58000,2023-07-02,52200.0,58000
2,O1003,C003,Tablet,3,15000,2023-05-01,13500.0,45000
4,O1005,C005,Mobile,2,22000,2023-06-05,19800.0,44000
7,O1008,C008,Tablet,2,18000,2023-07-20,16200.0,36000
1,O1002,C002,Mobile,1,25000,2023-04-12,22500.0,25000
5,O1006,C006,Headphones,5,2000,2023-06-10,1800.0,10000

In [62]:
sales_with_region = pd.merge(sales, customer, on="CustomerID", how="left")

In [63]:
sales_with_region

,OrderID,CustomerID,Product,Quantity,Price,OrderDate,discount,revenue,Name,Age,Region,SignupDate
0,O1001,C001,Laptop,2,55000,2023-04-10,49500.0,110000,Amit,None,North,2023-01-15
1,O1002,C002,Mobile,1,25000,2023-04-12,22500.0,25000,Priya,None,South,2022-11-20
2,O1003,C003,Tablet,3,15000,2023-05-01,13500.0,45000,John,None,East,2023-03-05
3,O1004,C004,Laptop,1,60000,2023-05-15,54000.0,60000,Sara,None,West,2021-07-12
4,O1005,C005,Mobile,2,22000,2023-06-05,19800.0,44000,David,None,North,2023-02-10
5,O1006,C006,Headphones,5,2000,2023-06-10,1800.0,10000,Meera,None,South,2022-09-18
6,O1007,C007,Laptop,1,58000,2023-07-02,52200.0,58000,Alex,None,East,2023-01-25
7,O1008,C008,Tablet,2,18000,2023-07-20,16200.0,36000,Ravi,None,West,2022-12-01

In [64]:
region_avg_revenue = sales_with_region.groupby("Region")['revenue'].mean()
print(region_avg_revenue)

Region
East     51500.0
North    77000.0
South    17500.0
West     48000.0
Name: revenue, dtype: float64

In [65]:
support_avg_time = support.groupby("IssueType")['ResolutionTime'].mean()
print(support_avg_time)

IssueType
Delivery Delay    38.000000
Payment Issue     18.666667
Product Defect    66.000000
Name: ResolutionTime, dtype: float64

**data wrangling

In [71]:
median_age = customer['Age'].dropna().median()
print(median_age)

nan

In [69]:
customer['Age'].fillna(median_age, inplace=True)

In [70]:
customer

  CustomerID   Name  Age Region SignupDate
0       C001   Amit  NaN  North 2023-01-15
1       C002  Priya  NaN  South 2022-11-20
2       C003   John  NaN   East 2023-03-05
3       C004   Sara  NaN   West 2021-07-12
4       C005  David  NaN  North 2023-02-10
5       C006  Meera  NaN  South 2022-09-18
6       C007   Alex  NaN   East 2023-01-25
7       C008   Ravi  NaN   West 2022-12-01