In [1]:
print("hello world")

hello world

In [2]:
import pandas as pd
import numpy as np

In [5]:
s=pd.Series([1,2,3,4,5,6])

In [6]:
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
df=pd.DataFrame(np.random.rand(40,5))

In [9]:
df

           0         1         2         3         4
0   0.226416  0.407226  0.711010  0.956574  0.458486
1   0.801928  0.893238  0.228686  0.804173  0.360654
2   0.385011  0.682505  0.336346  0.025529  0.435515
3   0.771576  0.547344  0.499090  0.753029  0.860993
4   0.311800  0.947751  0.390997  0.222175  0.047195
5   0.793170  0.604318  0.568441  0.980608  0.228129
6   0.890669  0.519398  0.072819  0.544515  0.590018
7   0.753737  0.727452  0.118360  0.028287  0.885134
8   0.064545  0.911368  0.328367  0.357828  0.275949
9   0.862354  0.418945  0.380652  0.808600  0.716183
10  0.419485  0.647974  0.286545  0.491550  0.670699
11  0.875484  0.878015  0.372406  0.814145  0.680218
12  0.006387  0.104695  0.527630  0.754343  0.910505
13  0.944397  0.268481  0.101828  0.411673  0.637899
14  0.022872  0.700721  0.914714  0.107228  0.573317
15  0.427542  0.614557  0.075360  0.465118  0.700397
16  0.823050  0.564705  0.289591  0.861623  0.773211
17  0.854096  0.993126  0.961259  0.043739  0.079103
18  0.399077  0.656156  0.246922  0.192029  0.404321
19  0.052903  0.343673  0.576580  0.366800  0.473818
20  0.963215  0.340794  0.047535  0.217161  0.215103
21  0.940068  0.644520  0.394629  0.296685  0.547998
22  0.842096  0.100480  0.375974  0.190216  0.173402
23  0.445258  0.369507  0.277690  0.909063  0.394518
24  0.873495  0.122853  0.588924  0.181026  0.198453
25  0.399282  0.052909  0.600741  0.987437  0.885978
26  0.972185  0.233366  0.887174  0.155608  0.050258
27  0.500998  0.115393  0.427573  0.258816  0.447454
28  0.427196  0.970634  0.197675  0.754323  0.569217
29  0.072861  0.871536  0.617203  0.144060  0.665989
30  0.191819  0.906214  0.804801  0.744465  0.212300
31  0.719196  0.491738  0.366380  0.472145  0.424347
32  0.929266  0.571385  0.792539  0.462282  0.864986
33  0.752903  0.807827  0.906517  0.512871  0.701189
34  0.159696  0.670706  0.454984  0.979554  0.970685
35  0.158482  0.083459  0.970244  0.655072  0.837706
36  0.042164  0.246857  0.665914  0.967900  0.771261
37  0.416193  0.386487  0.109810  0.749150  0.631559
38  0.393727  0.808880  0.432461  0.046664  0.883824
39  0.680778  0.916064  0.817837  0.862875  0.694473

In [10]:
df.head

<bound method NDFrame.head of            0         1         2         3         4
0   0.226416  0.407226  0.711010  0.956574  0.458486
1   0.801928  0.893238  0.228686  0.804173  0.360654
2   0.385011  0.682505  0.336346  0.025529  0.435515
3   0.771576  0.547344  0.499090  0.753029  0.860993
4   0.311800  0.947751  0.390997  0.222175  0.047195
5   0.793170  0.604318  0.568441  0.980608  0.228129
6   0.890669  0.519398  0.072819  0.544515  0.590018
7   0.753737  0.727452  0.118360  0.028287  0.885134
8   0.064545  0.911368  0.328367  0.357828  0.275949
9   0.862354  0.418945  0.380652  0.808600  0.716183
10  0.419485  0.647974  0.286545  0.491550  0.670699
11  0.875484  0.878015  0.372406  0.814145  0.680218
12  0.006387  0.104695  0.527630  0.754343  0.910505
13  0.944397  0.268481  0.101828  0.411673  0.637899
14  0.022872  0.700721  0.914714  0.107228  0.573317
15  0.427542  0.614557  0.075360  0.465118  0.700397
16  0.823050  0.564705  0.289591  0.861623  0.773211
17  0.854096  0.993126  0.961259  0.043739  0.079103
18  0.399077  0.656156  0.246922  0.192029  0.404321
19  0.052903  0.343673  0.576580  0.366800  0.473818
20  0.963215  0.340794  0.047535  0.217161  0.215103
21  0.940068  0.644520  0.394629  0.296685  0.547998
22  0.842096  0.100480  0.375974  0.190216  0.173402
23  0.445258  0.369507  0.277690  0.909063  0.394518
24  0.873495  0.122853  0.588924  0.181026  0.198453
25  0.399282  0.052909  0.600741  0.987437  0.885978
26  0.972185  0.233366  0.887174  0.155608  0.050258
27  0.500998  0.115393  0.427573  0.258816  0.447454
28  0.427196  0.970634  0.197675  0.754323  0.569217
29  0.072861  0.871536  0.617203  0.144060  0.665989
30  0.191819  0.906214  0.804801  0.744465  0.212300
31  0.719196  0.491738  0.366380  0.472145  0.424347
32  0.929266  0.571385  0.792539  0.462282  0.864986
33  0.752903  0.807827  0.906517  0.512871  0.701189
34  0.159696  0.670706  0.454984  0.979554  0.970685
35  0.158482  0.083459  0.970244  0.655072  0.837706
36  0.042164  0.246857  0.665914  0.967900  0.771261
37  0.416193  0.386487  0.109810  0.749150  0.631559
38  0.393727  0.808880  0.432461  0.046664  0.883824
39  0.680778  0.916064  0.817837  0.862875  0.694473>

In [11]:
df.head(10)

          0         1         2         3         4
0  0.226416  0.407226  0.711010  0.956574  0.458486
1  0.801928  0.893238  0.228686  0.804173  0.360654
2  0.385011  0.682505  0.336346  0.025529  0.435515
3  0.771576  0.547344  0.499090  0.753029  0.860993
4  0.311800  0.947751  0.390997  0.222175  0.047195
5  0.793170  0.604318  0.568441  0.980608  0.228129
6  0.890669  0.519398  0.072819  0.544515  0.590018
7  0.753737  0.727452  0.118360  0.028287  0.885134
8  0.064545  0.911368  0.328367  0.357828  0.275949
9  0.862354  0.418945  0.380652  0.808600  0.716183

In [12]:
df.tail(5)

           0         1         2         3         4
35  0.158482  0.083459  0.970244  0.655072  0.837706
36  0.042164  0.246857  0.665914  0.967900  0.771261
37  0.416193  0.386487  0.109810  0.749150  0.631559
38  0.393727  0.808880  0.432461  0.046664  0.883824
39  0.680778  0.916064  0.817837  0.862875  0.694473

In [13]:
df.describe()

               0          1          2          3          4
count  40.000000  40.000000  40.000000  40.000000  40.000000
mean    0.539184   0.553581   0.468105   0.513423   0.547561
std     0.323646   0.286629   0.269001   0.321685   0.263415
min     0.006387   0.052909   0.047535   0.025529   0.047195
25%     0.290454   0.342953   0.284331   0.210878   0.386052
50%     0.473128   0.587851   0.411101   0.481848   0.581667
75%     0.845096   0.808091   0.629381   0.805280   0.729953
max     0.972185   0.993126   0.970244   0.987437   0.970685

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       40 non-null     float64
 1   1       40 non-null     float64
 2   2       40 non-null     float64
 3   3       40 non-null     float64
 4   4       40 non-null     float64
dtypes: float64(5)
memory usage: 1.7 KB

**data selection

In [18]:
type(df["id"])

KeyError: 'id'

In [20]:
df.iloc[0]

0    0.226416
1    0.407226
2    0.711010
3    0.956574
4    0.458486
Name: 0, dtype: float64

In [22]:
type(df.iloc[0])

pandas.core.series.Series

In [23]:
df.dropna()

           0         1         2         3         4
0   0.226416  0.407226  0.711010  0.956574  0.458486
1   0.801928  0.893238  0.228686  0.804173  0.360654
2   0.385011  0.682505  0.336346  0.025529  0.435515
3   0.771576  0.547344  0.499090  0.753029  0.860993
4   0.311800  0.947751  0.390997  0.222175  0.047195
5   0.793170  0.604318  0.568441  0.980608  0.228129
6   0.890669  0.519398  0.072819  0.544515  0.590018
7   0.753737  0.727452  0.118360  0.028287  0.885134
8   0.064545  0.911368  0.328367  0.357828  0.275949
9   0.862354  0.418945  0.380652  0.808600  0.716183
10  0.419485  0.647974  0.286545  0.491550  0.670699
11  0.875484  0.878015  0.372406  0.814145  0.680218
12  0.006387  0.104695  0.527630  0.754343  0.910505
13  0.944397  0.268481  0.101828  0.411673  0.637899
14  0.022872  0.700721  0.914714  0.107228  0.573317
15  0.427542  0.614557  0.075360  0.465118  0.700397
16  0.823050  0.564705  0.289591  0.861623  0.773211
17  0.854096  0.993126  0.961259  0.043739  0.079103
18  0.399077  0.656156  0.246922  0.192029  0.404321
19  0.052903  0.343673  0.576580  0.366800  0.473818
20  0.963215  0.340794  0.047535  0.217161  0.215103
21  0.940068  0.644520  0.394629  0.296685  0.547998
22  0.842096  0.100480  0.375974  0.190216  0.173402
23  0.445258  0.369507  0.277690  0.909063  0.394518
24  0.873495  0.122853  0.588924  0.181026  0.198453
25  0.399282  0.052909  0.600741  0.987437  0.885978
26  0.972185  0.233366  0.887174  0.155608  0.050258
27  0.500998  0.115393  0.427573  0.258816  0.447454
28  0.427196  0.970634  0.197675  0.754323  0.569217
29  0.072861  0.871536  0.617203  0.144060  0.665989
30  0.191819  0.906214  0.804801  0.744465  0.212300
31  0.719196  0.491738  0.366380  0.472145  0.424347
32  0.929266  0.571385  0.792539  0.462282  0.864986
33  0.752903  0.807827  0.906517  0.512871  0.701189
34  0.159696  0.670706  0.454984  0.979554  0.970685
35  0.158482  0.083459  0.970244  0.655072  0.837706
36  0.042164  0.246857  0.665914  0.967900  0.771261
37  0.416193  0.386487  0.109810  0.749150  0.631559
38  0.393727  0.808880  0.432461  0.046664  0.883824
39  0.680778  0.916064  0.817837  0.862875  0.694473

In [24]:
df.fillna(0, inplace=True)

** inplace changes into origibal data fraame , so it is not recommendable to use

**for chnaging coloumn name = df.rename(coloumns={"original name":"newname"},inplace=True)# inplace is used to do changes in origibal dta frame

In [25]:
df.describe()

               0          1          2          3          4
count  40.000000  40.000000  40.000000  40.000000  40.000000
mean    0.539184   0.553581   0.468105   0.513423   0.547561
std     0.323646   0.286629   0.269001   0.321685   0.263415
min     0.006387   0.052909   0.047535   0.025529   0.047195
25%     0.290454   0.342953   0.284331   0.210878   0.386052
50%     0.473128   0.587851   0.411101   0.481848   0.581667
75%     0.845096   0.808091   0.629381   0.805280   0.729953
max     0.972185   0.993126   0.970244   0.987437   0.970685

In [26]:
df.info

<bound method DataFrame.info of            0         1         2         3         4
0   0.226416  0.407226  0.711010  0.956574  0.458486
1   0.801928  0.893238  0.228686  0.804173  0.360654
2   0.385011  0.682505  0.336346  0.025529  0.435515
3   0.771576  0.547344  0.499090  0.753029  0.860993
4   0.311800  0.947751  0.390997  0.222175  0.047195
5   0.793170  0.604318  0.568441  0.980608  0.228129
6   0.890669  0.519398  0.072819  0.544515  0.590018
7   0.753737  0.727452  0.118360  0.028287  0.885134
8   0.064545  0.911368  0.328367  0.357828  0.275949
9   0.862354  0.418945  0.380652  0.808600  0.716183
10  0.419485  0.647974  0.286545  0.491550  0.670699
11  0.875484  0.878015  0.372406  0.814145  0.680218
12  0.006387  0.104695  0.527630  0.754343  0.910505
13  0.944397  0.268481  0.101828  0.411673  0.637899
14  0.022872  0.700721  0.914714  0.107228  0.573317
15  0.427542  0.614557  0.075360  0.465118  0.700397
16  0.823050  0.564705  0.289591  0.861623  0.773211
17  0.854096  0.993126  0.961259  0.043739  0.079103
18  0.399077  0.656156  0.246922  0.192029  0.404321
19  0.052903  0.343673  0.576580  0.366800  0.473818
20  0.963215  0.340794  0.047535  0.217161  0.215103
21  0.940068  0.644520  0.394629  0.296685  0.547998
22  0.842096  0.100480  0.375974  0.190216  0.173402
23  0.445258  0.369507  0.277690  0.909063  0.394518
24  0.873495  0.122853  0.588924  0.181026  0.198453
25  0.399282  0.052909  0.600741  0.987437  0.885978
26  0.972185  0.233366  0.887174  0.155608  0.050258
27  0.500998  0.115393  0.427573  0.258816  0.447454
28  0.427196  0.970634  0.197675  0.754323  0.569217
29  0.072861  0.871536  0.617203  0.144060  0.665989
30  0.191819  0.906214  0.804801  0.744465  0.212300
31  0.719196  0.491738  0.366380  0.472145  0.424347
32  0.929266  0.571385  0.792539  0.462282  0.864986
33  0.752903  0.807827  0.906517  0.512871  0.701189
34  0.159696  0.670706  0.454984  0.979554  0.970685
35  0.158482  0.083459  0.970244  0.655072  0.837706
36  0.042164  0.246857  0.665914  0.967900  0.771261
37  0.416193  0.386487  0.109810  0.749150  0.631559
38  0.393727  0.808880  0.432461  0.046664  0.883824
39  0.680778  0.916064  0.817837  0.862875  0.694473>

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       40 non-null     float64
 1   1       40 non-null     float64
 2   2       40 non-null     float64
 3   3       40 non-null     float64
 4   4       40 non-null     float64
dtypes: float64(5)
memory usage: 1.7 KB

** for changing coloumn datatype df.['coloumnname']=df.['coloumnname'].astype(new datatype)

len(df)** gives rows

In [31]:
df["zeros"]= [0 for i in range(len(df))]

In [32]:
df

           0         1         2         3         4  zeros
0   0.226416  0.407226  0.711010  0.956574  0.458486      0
1   0.801928  0.893238  0.228686  0.804173  0.360654      0
2   0.385011  0.682505  0.336346  0.025529  0.435515      0
3   0.771576  0.547344  0.499090  0.753029  0.860993      0
4   0.311800  0.947751  0.390997  0.222175  0.047195      0
5   0.793170  0.604318  0.568441  0.980608  0.228129      0
6   0.890669  0.519398  0.072819  0.544515  0.590018      0
7   0.753737  0.727452  0.118360  0.028287  0.885134      0
8   0.064545  0.911368  0.328367  0.357828  0.275949      0
9   0.862354  0.418945  0.380652  0.808600  0.716183      0
10  0.419485  0.647974  0.286545  0.491550  0.670699      0
11  0.875484  0.878015  0.372406  0.814145  0.680218      0
12  0.006387  0.104695  0.527630  0.754343  0.910505      0
13  0.944397  0.268481  0.101828  0.411673  0.637899      0
14  0.022872  0.700721  0.914714  0.107228  0.573317      0
15  0.427542  0.614557  0.075360  0.465118  0.700397      0
16  0.823050  0.564705  0.289591  0.861623  0.773211      0
17  0.854096  0.993126  0.961259  0.043739  0.079103      0
18  0.399077  0.656156  0.246922  0.192029  0.404321      0
19  0.052903  0.343673  0.576580  0.366800  0.473818      0
20  0.963215  0.340794  0.047535  0.217161  0.215103      0
21  0.940068  0.644520  0.394629  0.296685  0.547998      0
22  0.842096  0.100480  0.375974  0.190216  0.173402      0
23  0.445258  0.369507  0.277690  0.909063  0.394518      0
24  0.873495  0.122853  0.588924  0.181026  0.198453      0
25  0.399282  0.052909  0.600741  0.987437  0.885978      0
26  0.972185  0.233366  0.887174  0.155608  0.050258      0
27  0.500998  0.115393  0.427573  0.258816  0.447454      0
28  0.427196  0.970634  0.197675  0.754323  0.569217      0
29  0.072861  0.871536  0.617203  0.144060  0.665989      0
30  0.191819  0.906214  0.804801  0.744465  0.212300      0
31  0.719196  0.491738  0.366380  0.472145  0.424347      0
32  0.929266  0.571385  0.792539  0.462282  0.864986      0
33  0.752903  0.807827  0.906517  0.512871  0.701189      0
34  0.159696  0.670706  0.454984  0.979554  0.970685      0
35  0.158482  0.083459  0.970244  0.655072  0.837706      0
36  0.042164  0.246857  0.665914  0.967900  0.771261      0
37  0.416193  0.386487  0.109810  0.749150  0.631559      0
38  0.393727  0.808880  0.432461  0.046664  0.883824      0
39  0.680778  0.916064  0.817837  0.862875  0.694473      0

In [37]:
df.rename(columns={"zeros":"ones"},inplace=True)

In [38]:
df.head(5)

          0         1         2         3         4  ones
0  0.226416  0.407226  0.711010  0.956574  0.458486     0
1  0.801928  0.893238  0.228686  0.804173  0.360654     0
2  0.385011  0.682505  0.336346  0.025529  0.435515     0
3  0.771576  0.547344  0.499090  0.753029  0.860993     0
4  0.311800  0.947751  0.390997  0.222175  0.047195     0

In [42]:
def fx(a):
    return a**a
df["ones +1 "]=df["o"].apply(fx)

KeyError: '3'

In [41]:
df

           0         1         2         3         4  ones  ones +1
0   0.226416  0.407226  0.711010  0.956574  0.458486     0         1
1   0.801928  0.893238  0.228686  0.804173  0.360654     0         1
2   0.385011  0.682505  0.336346  0.025529  0.435515     0         1
3   0.771576  0.547344  0.499090  0.753029  0.860993     0         1
4   0.311800  0.947751  0.390997  0.222175  0.047195     0         1
5   0.793170  0.604318  0.568441  0.980608  0.228129     0         1
6   0.890669  0.519398  0.072819  0.544515  0.590018     0         1
7   0.753737  0.727452  0.118360  0.028287  0.885134     0         1
8   0.064545  0.911368  0.328367  0.357828  0.275949     0         1
9   0.862354  0.418945  0.380652  0.808600  0.716183     0         1
10  0.419485  0.647974  0.286545  0.491550  0.670699     0         1
11  0.875484  0.878015  0.372406  0.814145  0.680218     0         1
12  0.006387  0.104695  0.527630  0.754343  0.910505     0         1
13  0.944397  0.268481  0.101828  0.411673  0.637899     0         1
14  0.022872  0.700721  0.914714  0.107228  0.573317     0         1
15  0.427542  0.614557  0.075360  0.465118  0.700397     0         1
16  0.823050  0.564705  0.289591  0.861623  0.773211     0         1
17  0.854096  0.993126  0.961259  0.043739  0.079103     0         1
18  0.399077  0.656156  0.246922  0.192029  0.404321     0         1
19  0.052903  0.343673  0.576580  0.366800  0.473818     0         1
20  0.963215  0.340794  0.047535  0.217161  0.215103     0         1
21  0.940068  0.644520  0.394629  0.296685  0.547998     0         1
22  0.842096  0.100480  0.375974  0.190216  0.173402     0         1
23  0.445258  0.369507  0.277690  0.909063  0.394518     0         1
24  0.873495  0.122853  0.588924  0.181026  0.198453     0         1
25  0.399282  0.052909  0.600741  0.987437  0.885978     0         1
26  0.972185  0.233366  0.887174  0.155608  0.050258     0         1
27  0.500998  0.115393  0.427573  0.258816  0.447454     0         1
28  0.427196  0.970634  0.197675  0.754323  0.569217     0         1
29  0.072861  0.871536  0.617203  0.144060  0.665989     0         1
30  0.191819  0.906214  0.804801  0.744465  0.212300     0         1
31  0.719196  0.491738  0.366380  0.472145  0.424347     0         1
32  0.929266  0.571385  0.792539  0.462282  0.864986     0         1
33  0.752903  0.807827  0.906517  0.512871  0.701189     0         1
34  0.159696  0.670706  0.454984  0.979554  0.970685     0         1
35  0.158482  0.083459  0.970244  0.655072  0.837706     0         1
36  0.042164  0.246857  0.665914  0.967900  0.771261     0         1
37  0.416193  0.386487  0.109810  0.749150  0.631559     0         1
38  0.393727  0.808880  0.432461  0.046664  0.883824     0         1
39  0.680778  0.916064  0.817837  0.862875  0.694473     0         1

In [3]:
df_students = pd.DataFrame({
    "student_id": [1, 2, 3, 4],
    "name": ["Ankit", "Riya", "Rahul", "Sneha"],
    "age": [21, 22, 20, 23]
})

In [4]:
df_marks = pd.DataFrame({
    "student_id": [1, 2, 4, 5],
    "math_marks": [85, 90, 88, 76]
})

In [5]:
df_students

   student_id   name  age
0           1  Ankit   21
1           2   Riya   22
2           3  Rahul   20
3           4  Sneha   23

In [6]:
df_marks

   student_id  math_marks
0           1          85
1           2          90
2           4          88
3           5          76

In [8]:
pd.concat([df_marks,df_students])

   student_id  math_marks   name   age
0           1        85.0    NaN   NaN
1           2        90.0    NaN   NaN
2           4        88.0    NaN   NaN
3           5        76.0    NaN   NaN
0           1         NaN  Ankit  21.0
1           2         NaN   Riya  22.0
2           3         NaN  Rahul  20.0
3           4         NaN  Sneha  23.0

In [10]:
pd.merge(df_students,df_marks, on="student_id")

   student_id   name  age  math_marks
0           1  Ankit   21          85
1           2   Riya   22          90
2           4  Sneha   23          88